name: Run order-crawl every 10min

on:
  schedule:
    - cron: "*/10 7-15 * * *"  # â° ì˜¤ì „ 7ì‹œë¶€í„° ì˜¤í›„ 3ì‹œê¹Œì§€ 10ë¶„ ê°„ê²©
  workflow_dispatch:           # ðŸ–± ìˆ˜ë™ ì‹¤í–‰ë„ ê°€ëŠ¥

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > credentials.json

      - name: Run crawler
        run: |
          node index.js
